SET SERVEROUTPUT ON;

------------------------------------------------------------ CRUD USUARIOS - CLIENTE -------------------------------------------------------------------

DECLARE 
    tp_PROFESIONAL PKG_SOLVEXTI_USUARIO.tp_PROFESIONAL;
    
BEGIN
    TP_PROFESIONAL.USERNAME := 'ADELPINO1';
    TP_PROFESIONAL.PASSWORD := 'ADELPINO1';
    TP_PROFESIONAL.TELEFONO := '942035153';
    TP_PROFESIONAL.CORREO := 'adelpino1@duoc.cl';
    TP_PROFESIONAL.ROL := 'Profesional';
    TP_PROFESIONAL.NOMBRE := 'Alejandro';
    TP_PROFESIONAL.APELLIDO_PATERNO := 'Del Pino';
    TP_PROFESIONAL.APELLIDO_MATERNO := 'Acevedo';
    TP_PROFESIONAL.RUT := '19307652';
    TP_PROFESIONAL.DV := '1';
    
    PKG_SOLVEXTI_USUARIO.PR_INSERTAR_PROFESIONAL(TP_PROFESIONAL);
    
    
    
    DBMS_OUTPUT.PUT_LINE('QWE'||TP_PROFESIONAL.USERNAME);
END;
/


INSERT INTO USUARIO (ID_USUARIO,username, PASSWORD, TELEFONO, CORREO, ID_ROL) 
         VALUES(2,'ADELPINO1','ADELPINO1', '942035153', 'ADELPINO1@DUOC.CL', 2);
