
EXECUTE  PR_INSERTAR_USUARIO ('ALB.DELPINO', 'ALB.DELPINO', '+56942035153', 'ALB.DELPINO@ALUMNOS.DUOC.CL', 3);
EXECUTE  PR_INSERTAR_PROFESIONAL ('ALEJANDRO', 'DEL PINO', 'ACEVEDO', 19307652, '1');


DESC cliente;

declare
v_usuario usuario%ROWTYPE;
begin
v_usuario := FN_OBTENER_USUARIO('AL.DELPINO');
end;