/**************************************************************************************************************
   NAME:        Secuencias
   PURPOSE		Gestiona secuencias de la base de datos Solvexti

   REVISIONS:
   Ver          Date           Author                               Description
   ---------    ----------     -------------------                  ----------------------------------------------
   1.1.1-1.1    02/06/2020     Alejandro Del Pino       			1. Creacion de Secuencias

***************************************************************************************************************/

 SEQUENCE ID_ACTIVIDAD_SEQ;
 SEQUENCE ID_BOLETA_SEQ;
 SEQUENCE ID_CLIENTE_SEQ;
 SEQUENCE ID_CONTRATO_SEQ;
 SEQUENCE ID_INCIDENTE_SEQ;
 SEQUENCE ID_MODIFICACION;
 SEQUENCE ID_PUNTO_MEJORABLE_SEQ;
 SEQUENCE ID_ROL_SEQ;
 SEQUENCE ID_TIPO_ACTIVIDAD_SEQ;
 SEQUENCE ID_TRABAJADOR_SEQ;
 SEQUENCE ID_USUARIO_SEQ;
 SEQUENCE ID_NOTIFICACION_SEQ;
 SEQUENCE ID_PLAN_SEQ;
 SEQUENCE ID_PROFESIONAL_SEQ;



 CREATE SEQUENCE ID_ACTIVIDAD_SEQ START WITH 1;
 CREATE SEQUENCE ID_BOLETA_SEQ START WITH 1;
 CREATE SEQUENCE ID_CLIENTE_SEQ START WITH 1;
 CREATE SEQUENCE ID_CONTRATO_SEQ START WITH 1;
 CREATE SEQUENCE ID_INCIDENTE_SEQ START WITH 1;
 CREATE SEQUENCE ID_MODIFICACION START WITH 1;
 CREATE SEQUENCE ID_PUNTO_MEJORABLE_SEQ START WITH 1;
 CREATE SEQUENCE ID_ROL_SEQ START WITH 1;
 CREATE SEQUENCE ID_TIPO_ACTIVIDAD_SEQ START WITH 1;
 CREATE SEQUENCE ID_TRABAJADOR_SEQ START WITH 1;
 CREATE SEQUENCE ID_USUARIO_SEQ START WITH 1;
 CREATE SEQUENCE ID_NOTIFICACION_SEQ START WITH 1;
 CREATE SEQUENCE ID_PLAN_SEQ START WITH 1;
 CREATE SEQUENCE ID_PROFESIONAL_SEQ START WITH 1;


COMMIT;
